scalar DateTime

type Query {
    #Auditorias
    findAllAuditorias : [Auditoria],
    findAuditoriasByTipoOperacion(tipoOperacion: String) : [Auditoria],
    findAuditoriasByFechaBetween(fechaInicial: DateTime, fechaFinal: DateTime) : [Auditoria],
    findAuditoriasByTabla(tabla: String) : [Auditoria],
    findAuditoriasByUsuario(usuario: String) : [Auditoria]

    #VistaInventarioItem
    findAllVistaInventarioItem : [VistaInventarioItem]

    #Estado
    findAllEstados : [Estado],
    findEstadoByNombre(nombre: String) : Estado,
    findEstadosByNombreContaining(nombre: String) : [Estado]

    #Subarea
    findAllSubareas : [Subarea],
    findSubareaByNombre(nombre: String) : Subarea,
    findSubareasByNombreContaining(nombre: String) : [Subarea]
}

type Auditoria {
    id: ID
    tabla: String
    tipoOperacion: String
    datosAnteriores: String
    datosNuevos: String
    usuario: String
    fecha: DateTime
}

type VistaInventarioItem {
    numeroItem: ID
    inventarioNombre: String
    estadoItem: String
    itemNombre: String
    subAreas: String
    cantidad: Int
    descripcion: String
    observaciones: String
    fechaCreacion: DateTime
    ultimaActualizacion: DateTime
    foto: String
}

type Estado {
    id: ID
    nombre: String
}

type Subarea {
    id: ID
    nombre: String
}
